version: '3.6'

services:
    api:
        container_name: book-api
        restart: always
        build: .
        ports:
            - 80:7000
        volumes:
            - ./:/go/src/github.com/book-api